// Generated by CoffeeScript 1.10.0
(function() {
  var calculation, hscore, hydrophobicity, i, len, leucine, output, residue_hscore, sequence, sequence_counter, sequence_position, txtInput, txtOutput;

  txtInput = document.getElementById('txtInput');

  txtOutput = document.getElementById('txtOutput');

  sequence = txtInput.value;

  leucine = {
    0.632036342: 0.632036342,
    0.86904997: 0.86904997,
    0.632036342: 0.632036342,
    0.632036342: 0.632036342,
    1.915860162: 1.915860162,
    2.824412404: 2.824412404,
    3.140430575: 3.140430575,
    3.29843966: 3.29843966,
    3.515702153: 3.515702153,
    3.357693067: 3.357693067,
    3.57495556: 3.57495556,
    3.772466917: 3.772466917,
    4.246494173: 4.246494173,
    4.009480545: 4.009480545,
    4.30574758: 4.30574758,
    4.048982817: 4.048982817,
    3.634208967: 3.634208967,
    3.239186253: 3.239186253,
    2.824412404: 2.824412404,
    2.982421489: 2.982421489,
    2.42938969: 2.42938969,
    2.70590559: 2.70590559,
    2.271380604: 2.271380604,
    2.646652183: 2.646652183,
    2.350385147: 2.350385147,
    1.876357891: 1.876357891,
    1.027059056: 1.027059056,
    0.770294292: 0.770294292,
    1.14556587: 1.14556587,
    1.14556587: 1.14556587,
    0.651787478: 0.651787478
  };

  hydrophobicity = [];

  sequence_counter = 0;

  hscore = [];

  for (i = 0, len = sequence.length; i < len; i++) {
    sequence_position = sequence[i];
    residue_hscore = 0;
    if (sequence_position === 'L') {
      residue_hscore = residue_hscore + leucine[sequence_position];
    }
    sequence_counter = sequence_counter + 1;
    hscore.push(residue_hscore);
  }

  calculation = hscore;

  output = calculation;

  txtOutput.value = output;

  return;

}).call(this);
